# -*- coding: utf-8 -*-
"""ocr_pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10fi0X1GS0eEgep9D3lVP6N7jEBIfAteB
"""

!apt-get install ocrmypdf -q

!pip install pdfplumber -q

import os
import json
import requests
import pdfplumber

# def download_file(url):
#     local_filename = url.split('/')[-1]

#     with requests.get(url) as r:
#         assert r.status_code == 200, f'error, status code is {r.status_code}'
#         with open(local_filename, 'wb') as f:
#             f.write(r.content)

#     return local_filename

invoice = 'https://bit.ly/2UJgUpO'
invoice_pdf = download_file(invoice)

with pdfplumber.open(invoice_pdf) as pdf:
    page = pdf.pages[0]
    text = page.extract_text()
    print(text)

os.system(f'ocrmypdf {invoice_pdf} output.pdf')

text_dict = {}

# STORING AS TEXT FILE

with pdfplumber.open('/content/drive/MyDrive/201202328.pdf') as pdf:
    page = pdf.pages[0]
    text = page.extract_text(x_tolerance=2)
    # print(text)
    output_text_file_path = '/content/drive/MyDrive/output_text.txt'
# Save the extracted text to a text file
with open(output_text_file_path, 'w') as file:
    file.write(text)

# Display a success message
print(f"Text has been saved to: {output_text_file_path}")

# STORING AS JSON FORMAT

with pdfplumber.open('/content/drive/MyDrive/201202328.pdf') as pdf:
    for page_number in range(len(pdf.pages)):
        page = pdf.pages[page_number]
        text = page.extract_text(x_tolerance=2)
        text_dict[f'page_{page_number + 1}'] = text

# Save the dictionary to a JSON file
json_path = '/content/drive/MyDrive/extracted_text.json'
with open(json_path, 'w') as json_file:
    json.dump(text_dict, json_file)

print(f'Text extracted from {len(pdf.pages)} pages and saved to {json_path}')

lines = text.split('\n')

lines

